# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: encrypt
  pool: 5
  username: root
  password: im
  host: localhost
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: encrypt
  pool: 5
  username: root
  password: im
  host: localhost
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: encrypt_test
  pool: 5
  username: root
  password: im
  host: localhost
